# Site settings
title: Title
email: Email@email.com
description: > # this means to ignore newlines until "baseurl:"
1234
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: ?
github_username:  ??

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
relative_permalinks: false
